spring:
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      port: 6379
      host: localhost